# Workflow for testing spoon code quality.
#
# Note that actions are specified by commit hash. This is to avoid the security
# risk of someone injecting malicious code into a release and then simply
# changing a tag.

name: Qodana
on:
  pull_request:
    branches:
      - master
jobs:
    code-quality:
      runs-on: ubuntu-latest
      name: code-quality qodana
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            fetch-depth: 0
        - name: 'Qodana Scan'
          uses: JetBrains/qodana-action@c96b39a84dea25f2a24b38a3f6e89903306d5e2a # v2024.1.8
          with:
            args: --source-directory,./src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-javadoc:
      runs-on: ubuntu-latest
      name: code-quality spoon-javadoc qodana
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-javadoc)'
          uses: JetBrains/qodana-action@c96b39a84dea25f2a24b38a3f6e89903306d5e2a # v2024.1.8
          with:
            args: --source-directory,./spoon-javadoc/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-control-flow:
      runs-on: ubuntu-latest
      name: code-quality spoon-controlflow qodana
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-control-flow)'
          uses: JetBrains/qodana-action@c96b39a84dea25f2a24b38a3f6e89903306d5e2a # v2024.1.8
          with:
            args: --source-directory,./spoon-control-flow/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
